.\"
.\" Copyright (c) 1996, 1997, 1998, 1999
.\"             Shigio Yamaguchi. All rights reserved.
.\" Copyright (c) 1999, 2000, 2001
.\"             Tama Communications Corporation. All rights reserved.
.\"
.\" This file is part of GNU GLOBAL.
.\"
.\" GNU GLOBAL is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2, or (at your option)
.\" any later version.
.\"
.\" GNU GLOBAL is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.Dd Jun 7, 2001
.Dt HTAGS 1
.Os FreeBSD
.Sh NAME
.Nm htags
.Nd generate hypertext from C, C++, Yacc, Java and assembler source code
.Sh SYNOPSIS
.Nm htags
.Op Fl a
.Op Fl c
.Op Fl f
.Op Fl F
.Op Fl l
.Op Fl n
.Op Fl v
.Op Fl s
.Op Fl w
.Op Fl d Ar tagdir
.Op Fl S Ar cgidir
.Op Fl t Ar title
.Op Ar dir
.Sh DESCRIPTION
.Nm Htags
makes hypertext from C, C++, Yacc and Java source code.
.Pp
In advance of using this command, you must execute
.Xr gtags 1
from the root directory of the source tree.
Then you can execute
.Nm htags
from the same place.
.Nm Htags
makes an HTML directory and generates hypertext in it.
.Pp
You can start browsing from 'HTML/index.html'.
Once the hypertext is generated, you can move it anywhere and browse it
with any browser.
.Pp
.br
.Bl -tag -width Ds -compact
.It Fl a
.It Fl -alphabet
Make an alphabetical function index, suitable for a large project.
.It Fl c
.It Fl -compact
Compress html files  by
.Xr gzip 1 .
You need to set up an HTTP server so that
.Xr gzip 1
is invoked for each compressed
file. See 'HTML/.htaccess' that is generated by htags.
.It Fl f
.It Fl -form
Support search form using CGI program.
You need to set up an HTTP server for this.
.It Fl F
.It Fl -frame
Use frame for each part of the contents.
.It Fl -gtagsconf Ar file
Load user's configuration from
.Ar file .
.It Fl l
.It Fl -each-line-tag
Make a name tag(<A NAME=line number>) for each line, so that other hypertext
can link to any line of this hypertext.
By default, htags makes it only for lines that are referred to.
.It Fl n
.It Fl -line-number
Print the line numbers. By default, doesn't print it.
.It Fl v
.It Fl -verbose
Verbose mode.
.It Fl w
.It Fl -warning
Print warning messages.
.It Fl d
.It Fl -dbpath Ar tagdir
Specifies the directory in which GTAGS and GRTAGS exist. The default is the
current directory.
.It Fl S
.It Fl -secure-cgi Ar cgidir
write cgi script into cgidir to realize a centralised cgi script.
Script alias is '/cgi-bin' by default. You can overwrite this value
with config variable 'script_alias' in global.conf.
.It Fl t
.It Fl -title Ar title
The title of this hypertext. The default is the last component of the
current directory.
.It Ar dir
The directory in which hypertext is generated. The default is the current
directory.
.El
.Sh EXAMPLES
  % cd /usr/src/sys
  # gtags -v
  # htags -fFnvat 'Welcom to FreeBSD kernel source tour!'
  % lynx HTML/index.html
.Sh FILES
.Bl -tag -width tags -compact
.It Pa HTML/index.html
Index file of hypertext.
.It Pa GTAGS
Tag file for function definitions.
.It Pa GRTAGS
Tag file for function references.
.It Pa GSYMS
Tag file for other symbols.
.It Pa GPATH
Tag file for path of source files.
.It Pa /etc/global.conf .globalrc
Configuration file.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of htags.
.Pp
.Bl -tag -width indent
.It Ev TMPDIR
If this variable is set, its value is used as the directory to make temporary files.
The default is /tmp.
.It Ev GTAGSCONF
If this variable is set, its value is used as the configuration file.
The default is $HOME/.globalrc.
.El
.Sh DIAGNOSTICS
.Nm Htags
exits with a non 0 value if an error occurred, 0 otherwise.
.Sh SEE ALSO
.Xr btreeop 1 ,
.Xr global 1 ,
.Xr gozilla 1 ,
.Xr gtags 1 .
.Sh BUG
Generated hypertext is VERY LARGE. In advance, check the space of your disk.
.Sh AUTHORS
Shigio Yamaguchi
.Sh HISTORY
The
.Nm
command appeared in FreeBSD 2.2.2.
