.\"
.\" Copyright (c) 1996, 1997, 1998, 1999
.\"             Shigio Yamaguchi. All rights reserved.
.\" Copyright (c) 1999, 2000
.\"             Tama Communications Corporation. All rights reserved.
.\"
.\" This file is part of GNU GLOBAL.
.\"
.\" GNU GLOBAL is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2, or (at your option)
.\" any later version.
.\"
.\" GNU GLOBAL is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.Dd Oct 10, 1999
.Dt GCTAGS 1
.Os FreeBSD
.Sh NAME
.Nm gctags
.Nd print cross reference list for gtags.
.Sh SYNOPSIS
.Nm gctags
.Op Fl b
.Op Fl e
.Op Fl n
.Op Fl r
.Op Fl s
.Op Fl w
.Ar file ...
.Sh DESCRIPTION
.Nm Gctags
print cross reference list for
.Xr gtags 1
from the specified C,
.Tn C++ ,
.Tn YACC ,
.Tn JAVA ,
and assembler source to standard output.
Each line of output contains the object name, the line number which it appears,
the file in which it is defined, and a line image separated by
white-space.
It's same with the output of
.Xr ctags 1
with -x option.
.Pp
Depending upon the options provided to
.Nm gctags ,
objects will consist of function definitions, function references and other
symbols.
This command is the default parser of GLOBAL source code tag system.
.Pp
.Bl -tag -width Ds -compact
.It Fl b
.It Fl -begin-block
Force level 1 block to begin when reach a '{' at the first column. (C only)
.It Fl e
.It Fl -end-block
Force level 1 block to end when reach a '}' at the first column. (C only)
.It Fl n
.It Fl -no-tags
Suppress output of tags. It is useful to use with
.Fl w
option.
.It Fl r
.It Fl -reference
Locate function references instead of function definitions. GTAGS file is
needed at the current directory. (C, C++ and Java source only)
By default, locate function definitions.
.It Fl s
.It Fl -symbol
Collect symbols other than functions. By default, locate function definitions.
.It Fl w
.It Fl -warning
Print warning message.
.El
.Pp
The
.Fl r
and
.Fl s
options override each other; the last one specified determines the method used.
.Pp
Files whose names end in
.Nm \&.c
or
.Nm \&.h
are assumed to be C
source files and are searched for C style routine and macro definitions.
Files whose names end in
.Nm \&.c++
.Nm \&.cc
.Nm \&.cpp
.Nm \&.cxx
.Nm \&.hxx
.Nm \&.C
.Nm \&.H
are assumed to be C++
source files.
Files whose names end in
.Nm \&.y
are assumed to be
.Tn YACC
source files.
Files whose names end in
.Nm \&.java
are assumed to be Java source files.
Files whose names end in
.Nm \&.s
or
.Nm \&.S
are assumed to be Assembler
source files.  Other files are searched for C style definitions.
.Pp
Yacc files each have a special tag.
.Ar Yyparse
is the start
of the second section of the yacc file.
.Sh DIAGNOSTICS
.Nm Gctags
exits with a non 0 value if an error occurred, 0 otherwise.
Duplicate objects are not considered errors.
.Sh SEE ALSO
.Xr btreeop 1 ,
.Xr ex 1 ,
.Xr global 1 ,
.Xr gtags 1 ,
.Xr htags 1 ,
.Xr vi 1 .
.Sh BUGS
.Pp
.Nm Gctags
relies on the input being well formed, and any syntactical
errors will completely confuse it.
.Pp
Assembler support is far from complete.  It extracts only ENTRY()
and ALTENTRY() from source file. Probably valid only for FreeBSD and Linux
kernel source.
.Sh AUTHORS
Shigio Yamaguchi (shigio@tamacom.com)
.Sh HISTORY
The
.Nm
command appeared in FreeBSD 2.2.2.
