#!/bin/sh
#
# client program for gtags, global, htags
#
host=${GTAGSREMOTEHOST}
user=${GTAGSREMOTEUSER}
shell=${GTAGSREMOTESHELL-ssh}
case $host in
'')	echo "Remote host is not specified."
	exit 1;;
esac
# Make command line.
command=`basename $0 | sed 's/-client//'`
arg=
for a in "$@"; do
	arg=$arg" '${a}'"
done
commandline="cd '`pwd`' && $command $arg"
case $user in
'')	$shell -q $host $commandline;;
*)	$shell -q -l $user $host $commandline;;
esac
